create table if not exists friendship
(
    id              bigint generated by default as identity PRIMARY KEY,
    requester       bigint not null ,
    addressee       bigint not null ,
    status          varchar(20) not null ,
    created_at      timestamp default current_timestamp,

    foreign key (requester) references users(id) on delete cascade,
    foreign key (addressee) references users(id) on delete cascade
);

comment on column friendship.requester is 'ID пользователя, отправившего заявку на дружбу';
comment on column friendship.addressee is 'ID пользователя, которому отправлена заявка';
comment on column friendship.status is 'Статус заявки';
comment on column friendship.created_at is 'Дата и время заявки';