create table if not exists subscription (
     id          bigint generated by default as identity primary key,
     target      bigint not null,
     subscriber  bigint not null,

     foreign key (target) references users(id) on delete cascade,
     foreign key (subscriber) references users(id) on delete cascade
);

comment on column subscription.target is 'ID пользователя, который подписался';
comment on column subscription.subscriber is 'ID пользователя, на которого подписались';